### ISSUE TITLE
serviceOptions 404 error

### ISSUE THREAD

**Issue by eugyev** [microsoft/chat-copilot#107]
**Describe the bug**
After deploying the package to Azure, the api/serviceOptions endpoint returns a 404.  If I run it from local files it works, but when using the package that is deployed to azure, it gives that error

<img width="1937" alt="image" src="https://github.com/microsoft/chat-copilot/assets/5740366/d2575694-c62b-4074-8312-1b13e21bad6b">

**To Reproduce**
1.  Deploy application using Azure 1 click deploy from the /deploy page
2. wait for webapi to deploy and build
3. go to webapi/healthz endpoint and it returns "healthy"
4. try to access webapi/serviceOptions endpoint and it returns a 404 error.  leads to error messages on client side

**Expected behavior**
Expect 200 response as when it is run locally

**Screenshots**
<img width="1937" alt="image" src="https://github.com/microsoft/chat-copilot/assets/5740366/d2575694-c62b-4074-8312-1b13e21bad6b">

**Platform**
- Azure

**Additional context**

**Comment by alliscode** [comment]
Hi @eugyev, thanks for creating this issue! 

Are you using the front-end webapp from the latest source code or from the latest [release](https://github.com/microsoft/chat-copilot/releases/tag/0731234103)? Since we add new features to the main branch every day, it's safest to use the front-end webapp that is packaged with the latest release as that matches the back-end webapi that gets deployed to Azure.

If you deployed to Azure within the last couple of days then you can find the release with the matching webapp [here](https://github.com/microsoft/chat-copilot/releases/tag/0731234103).

Let me know if this helps or not, thanks!

**Comment by eugyev** [comment]
Same error with deploying the webAPI from package file and frontend from the code as it is of the latest push to main.

**Comment by alliscode** [comment]
Ok we'll try to reproduce this and get back to you, thanks again.

**Comment by alliscode** [comment]
@eugyev in the meantime, you could deploy the latest webapi to your Azure instance using the deployment scripts as described [here](https://github.com/microsoft/chat-copilot/blob/main/deploy/README.md).

We also just published a new release so you could redeploy using the Deploy to Azure button. Hope that helps unblock you.

**Comment by eugyev** [comment]
new backend release from today fixed this. Thank you!
