### ISSUE TITLE
Web API as Function App ? 

### ISSUE THREAD

**Issue by kbeaugrand** [microsoft/chat-copilot#185]
Hi, I wondering to know why the web api has not been developed in Function App solution? 
Is there a specific requirement?

**Comment by crickman** [comment]
web api (as with any rest endpoint) can certainly be presented in conjunction with a http-trigger.  I suspect this more traditional route (app-service/rest api) was originally taken at the time for just that reason: familiarity - both customer and author.

Since Azure functions integrate tightly with the OpenAI plug-in model, you can expect to see more and more function usage as the semantic-kerneal and chat-copilot architecture evolve:

https://devblogs.microsoft.com/semantic-kernel/create-your-first-chatgpt-plugin-for-semantic-kernel/
https://devblogs.microsoft.com/semantic-kernel/test-your-chatgpt-plugins-in-the-updated-chat-copilot/
