### ISSUE TITLE
Output version != Actual response

### ISSUE THREAD

**Issue by miguelhermar** [microsoft/chat-copilot#221]
Hey, I'm using Stepwise Planner and I'm wondering why the output of Copilot is different from the final answer according to the Planner...would it have to do with the token limit or something like that and so it shrinks down the answer? or is it something else?
<img width="579" alt="Screenshot 2023-08-19 at 14 17 26" src="https://github.com/microsoft/chat-copilot/assets/63918608/5e049ff5-7bf3-415c-97f1-bb24c5183cd1">
<img width="978" alt="Screenshot 2023-08-19 at 14 18 49" src="https://github.com/microsoft/chat-copilot/assets/63918608/dcb09722-97d5-4e44-bfd6-b35dd48c250d">

**Comment by crickman** [comment]
It may be drawing information from chat history or some additional signal.  Could you provide the entire raw prompt?

**Comment by samleegithub** [comment]
@crickman I'm seeing the same problem too: #293

**Comment by teresaqhoang** [comment]
@miguelhermar @samleegithub This is expected because the planner serves to provide supplementary information to the greater bot response prompt. The Bot Response prompt is rendered after multiple calls to the LLM (i.e., user intent, audience extraction, memory extraction, planner external information).

So what happens here is the "Final Answer" of the Stepwise Planner is provided in the ExternalInformation section of the meta-prompt, and then this meta-prompt is passed to the LLM on the final pass and the completion of the meta-prompt template is what's used as the answer for CC. 

This is more clear if you look at the Raw Content tab, which is the raw meta-bot response prompt template that's passed to the LLM on the final hop. What's listed between `[Source Start]` and `[Source End]` is the result from the Stepwise Planner
![image](https://github.com/microsoft/chat-copilot/assets/125500434/6da0e516-5a7c-469f-b8c5-23a54f40afdf)
