### ISSUE TITLE
Cannot send data due to lost connection or server timeout. Try refreshing this page to restart the connection.

### ISSUE THREAD

**Issue by murdockcrc** [microsoft/chat-copilot#312]
**Describe the bug**
I am running the app on my local host. I created a devcontainer definition and run the app from there.

I run scripts/start.sh  and the app starts well, without issues or errors.

However, right when the webapp loads, I see this error immediately:

```
Cannot send data due to lost connection or server timeout. Try refreshing this page to restart the connection.
```

I can type a prompt in the text box and send it, but then the app gets stuck here:
<img width="635" alt="image" src="https://github.com/microsoft/chat-copilot/assets/4062119/d2577643-9afc-49ab-8cb8-1a8550912feb">

If I refresh the browser window, I can see a response from the model in the UI. It seems like the app is unable to handle the process of getting a response from the model as it is being generated. I do not see any errors on the frontend or backend app console messages.

On the browser's console, I only see this warning, and no other errors:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Ref which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
```

**Expected behavior**
The app is able to render the response generated by AOAI

**Platform**
 - OS: Debian 11 bullseye
 - IDE: vscode

**Comment by marcelojsilva** [comment]
I get the exactly same error.
Platform:
- OS: macOS 13.4.1
- Chip: M1
- IDE:VSCode

Someone can help?

**Comment by asabbott** [comment]
I was receiving the same error when using devcontainers within vscode until I setup a self-signed SSL certificate for localhost and switched ports of both webapp and webapi to run as HTTPS.

**Comment by dehoward** [comment]
@murdockcrc @marcelojsilva can you please try the suggestion above to see if it resolves your issue?

**Comment by glennelliott** [comment]
I'm getting this exact same issue on Mac. I tried asabbott's suggestion and I'm now using HTTPS, but the issue persists, no change.

**Comment by teresaqhoang** [comment]
Hey @murdockcrc @marcelojsilva @glennelliott, apologies for the delayed reply - our team doesn't have much bandwidth for Mac/Linux testing. @matthewbolanos and I will look into testing CC with dev containers more closely next week. 

Some questions I had:
- Do you see a page that says "Healthy" if you navigate to `https://localhost:40443`?
- Are you able to send a chat message? Or other chat operations like add a new chat?
- Is that error persistent (i.e., when you refresh the webapp client, is there still a connection error shown)? It looks like this is an issue with SignalR, which can be flaky when establishing the connection. 

tagging @dehoward for transparency since he's on our support rotation this week - can you try testing this with vscode dev containers on a windows machine?

**Comment by glennelliott** [comment]
Hey Teresa ... to answer your bullets in order:

- Yes, it's Healthy.
- Yes, all of those operations generally work. But when I submit a message, I need to refresh the page to see the response. It does sound like a SignalR issue as you say.
- It's quite persistent, but it doesn't happen 100% of the time. On occasion, the responses come through as expected, but mostly a refresh is needed.

I ended up deploying it all to Azure and working with it there, so as to bypass the local config challenges.

**Comment by evchaki** [comment]
please try this on the latest build to see if it is still happening.
