### ISSUE TITLE
WebAPI doesn't run after ./deploy-webapi.ps1 

### ISSUE THREAD

**Issue by raffertyuy** [microsoft/chat-copilot#387]
**Describe the bug**
Deploying the backend using ./deploy-webapi.ps1 leads to the site not running.
This is without code changes.

Log stream indicates that it is looking for the web.config?

**To Reproduce**
1. Deploy from https://learn.microsoft.com/en-us/semantic-kernel/chat-copilot/deploy-to-azure, Use existing: Azure OpenAI Resources
2. Clone the Repo
3. Go to `./scripts`
4. Configure `.\Configure.ps1 -AIService AzureOpenAI -APIKey VALUE -Endpoint VALUE -CompletionModel VALUE EmbeddingModel VALUE -PlannerModel VALUE -FrontendClientId VALUE -BackendClientId VALUE  -TenantId VALUE -Instance https://login.microsoftonline.com`
5. go to `./scripts/deploy`
6. Run `./package-webapi.ps1`
7. Run `./deploy-webapi.ps1 -Subscription VALUE  -ResourceGroupName VALUE  -DeploymentName VALUE `
8. Go to https://name.azurewebsites.net/healthz
9. See error

**Expected behavior**
API running successfully

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/1037626/8d591fe3-7e2f-430c-9ee0-9a8a9226b27e)

Here is the error from the Log Stream, seems like it is looking the web.config file?
![image](https://github.com/microsoft/chat-copilot/assets/1037626/76d27f8f-808b-476a-a275-3460e0f7e35d)

**Additional note**
These configurations were initially BLANK after deployment. I manually set these to .NET 6. Didn't fix the issue though.
![image](https://github.com/microsoft/chat-copilot/assets/1037626/35912bba-fad5-4da9-b07f-b484bf1ed512)

**Comment by raffertyuy** [comment]
I see the web.config is properly deployed. Issue is something else

**Comment by utkalext** [comment]
I was able to get past this error by setting my web app to .NET 7 (STS) (I'm running 0.5 that uses .Net 7), then re-deploying the webapi and restarting. The https://name.azurewebsites.net/healthz then comes up as Healthy. I can now login to the copilot app, but when I type a question it comes back with "Unable to generate both response. Details: Error: 500 Internal Server Error".

**Comment by raffertyuy** [comment]
> I was able to get past this error by setting my web app to .NET 7 (STS) (I'm running 0.5 that uses .Net 7), then re-deploying the webapi and restarting. The https://name.azurewebsites.net/healthz then comes up as Healthy. I can now login to the copilot app, but when I type a question it comes back with "Unable to generate both response. Details: Error: 500 Internal Server Error".

This didn't work for me...

**Comment by dehoward** [comment]
@raffertyuy thanks for reporting this.
we have been able to reproduce the issue and @glahaye is taking a look to determine the cause.

**Comment by glahaye** [comment]
@raffertyuy Thanks for raising this to our attention.

This is what is happening...  When using the "Deploy to Azure" button, an ARM template is used to deploy resources to your selected Azure resource group. These resources include the configuration settings used by the instance of webapi running online.  The ARM template is a snapshot of the ./scripts/deploy/main.json file found on this repo.

The snapshot is for version 0.4 of Chat Copilot. However, if you then run scripts from a command line using the latest version of the repo, the configuration settings don't match because a major, breaking change was introduced in version 0.5.

The ironic thing is that we left the ARM template (and a corresponding binary for webapi) sit at version 0.4 because we wanted to make sure that deployments would remain stable if something was not right with version 0.5 of the code.

However, this is precisely was is causing THIS issue with deployments.

To circumvent this problem now, you can first use the deploy-azure script (as opposed to the "Deploy to Azure" button) to deploy the resources in your resource group (you should be able to keep the same resource group) and then run deploy-webapi.  Since the scripts are both from the same version of the repo, the proper settings will be populated.

I will also go update the "Deploy to Azure" components to bring them up to date.  That will take care of the problem for now,

Then, I'll have to figure out a way to prevent this from being a problem in the future when other breaking changes are introduced,

**Comment by glahaye** [comment]
I've been instructed to wait until Monday to deploy updated components for the "Deploy to Azure" button.

So, again, to have things work for you now, simply use both the deploy-azure and deploy-webapi scripts from your machine and you should be good to go.

**Comment by rmaster-smirth** [comment]
When trying to use the deploy-azure script as a workaround for this I receive:

`{"code": "InvalidTemplateDeployment", "message": "The template deployment 'Microsoft.Template-xxx' is not valid according to the validation procedure. The tracking id is 'xxx'. See inner errors for details."}`

`Inner Errors:
{"code": "FlagMustBeSetForRestore", "message": "An existing resource with ID '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.CognitiveServices/accounts/cog-ocr-copichat-zwrkrfm4arkts' has been soft-deleted. To restore the resource, you must specify 'restore' to be 'true' in the property. If you don't want to restore existing resource, please purge it first."}
az_command_data_logger: {"code": "InvalidTemplateDeployment", "message": "The template deployment 'Microsoft.Template-xxx' is not valid according to the validation procedure. The tracking id is 'xxx'. See inner errors for details."}`

**Comment by glahaye** [comment]
@rmaster-smirth This will happen when you delete a cognitive services instance and then try to create a new one with the same name.

The easiest workaround is the create a new resource / deployment with a slightly different name.

Otherwise, you can look into the suggestion from the error message and "purge" the delete resource:
https://learn.microsoft.com/en-us/azure/ai-services/manage-resources?tabs=azure-portal
