### ISSUE TITLE
Question, How can i disable the react generated css class and see the griffel class ?

### ISSUE THREAD

**Issue by gavrielsl** [microsoft/chat-copilot#389]

**Comment by dehoward** [comment]
hi @gavrielsl, this unfortunately doesn't appear to be possible since `makeStyles` doesn't provide a way to opt-out of the classname generation. one approach you could take is assigning an `id`, `data-testid`, or some other identifiable HTML attribute that can help when looking at the DOM.
alternatively, if knowing the classname is a must for you, you can define classes in a CSS file and then import that file into the relevant component. notice how `src/index.tsx` is doing this with `index.css` for the `app-container` class.

hope this helps! I will close the issue for now but feel free to re-open it if you're still having issues.
