### ISSUE TITLE
Lightweight Frontend

### ISSUE THREAD

**Issue by victor-v-rad** [microsoft/chat-copilot#487]
Hi Team,

The Chat Copilot is a great, feature-rich reference app. It serves well as a standalone solution. I believe most the companies would want to incorporate its functionality into their existing projects. The backend is easy to run as a separate service, but the same cannot be said for the frontend. The frontend is a heavy bundle of tightly coupled React components, which makes it seem easier to write it from scratch than to reuse its code for integration into existing frontends. Please consider creating a lightweight and portable version of the frontend that retains the basic chat functionality or suggest other ideas.

**Comment by crickman** [comment]
@victor-v-rad - You may benefit to explore other chat options offered by Azure: 

https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart?tabs=command-line%2Cpython&pivots=programming-language-studio#playground

Chat copilot is intended to be a sample application for how to integrate semantic-kernel into a more full-featured application.  We understand that it cannot address all possible scenarios.  In addition, we recommend that customers/partners fork chat-copilot, if interested, since we do not recommend deploying directly.

**Comment by victor-v-rad** [comment]
Thanks @glahaye
