### ISSUE TITLE
A fresh frontend instance does not reflect globally uploaded available docs

### ISSUE THREAD

**Issue by momuno** [microsoft/chat-copilot#670]
**Describe the bug**
When starting a fresh frontend instance, prior globally uploaded docs are still available for reference.  However, these docs do not appear under the docs tab.

**To Reproduce**
1. Run chat copilot per quickstart instructions.
2. Upload a global document under the documents tab.
3. Start a fresh frontend.  
4. View documents tab -- no global documents are reported.
5. Ask a question of a previously globally uploaded document, and you will get a response with the doc referenced.

**Expected behavior**
The globally uploaded documents stored in the chat-memory should appear under docs tab.

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/64985898/26bedd84-49a0-4f99-ae65-d4e87ba5b80b)
![image](https://github.com/microsoft/chat-copilot/assets/64985898/02a6d429-b324-45fb-8f9b-a1c4f410c7ba)

**Platform**
 - OS: Windows 11
 - IDE: VSCode
 - Language: [e.g. C#, Python]
 - Source: Commit https://github.com/microsoft/chat-copilot/pull/588/commits/5ba7ed01068a2ffa4894331e5a6bd9a4420bcc17

**Comment by crickman** [comment]
This isn't due to memory management.  It is a side-effect of using the default `volatile` chat-store:

<img width="263" alt="image" src="https://github.com/microsoft/chat-copilot/assets/66376200/de15c5b1-9568-4c6c-91c6-21d1996ec5a2">

I suspect in the original case, both the webapi and webapp were restarted.  This results in a total resert of the `MemorySource` container (which lists all documents).   The content of the vector-database/embeddings, isn't altered by this reset process, however, so the document memories continue to persist in the chat experience.  Note: This issue only applies to the developer environment.

If only the webapp is restarted, or if a persistent chat-store is utilized...the list of documents in the `MemorySource` is preserved and displayed across application instances as expected.

Admittedly there'd be better parity if the vector embeddings were also defaulting to a "volatile' behavior.  @TaoChenOSU may have some insight as to wether this might be a quick change to the default configuration, or not.  Another work-around might be to simply delete the "./tmp" folder to reset the local memories/embeddings.

Here is my validation of this feature:

<img width="1020" alt="image" src="https://github.com/microsoft/chat-copilot/assets/66376200/dfc4f8b5-eaeb-466e-bc89-d7831718c50a">

### Summary
Working as designed.
