### ISSUE TITLE
Access denied due to invalid subscription key or wrong API endpoint.

### ISSUE THREAD

**Issue by sofiangava** [microsoft/chat-copilot#738]
I have started the backend and the front end separately and when the front end startsup I keep getting:        

---> Azure.RequestFailedException: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
      Status: 401 (PermissionDenied)
      ErrorCode: 401

I have tried stepping through the code to no avail, I have checked all my user secrets  and they all look populated and correct. Anyone else run into this issue?

Note I have even tried on a blank machine which has nothing on it in case there was some remnant left over causing issues.

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: [e.g. C#, Python]

**Comment by gitri-ms** [comment]
@sofiangava Could you point me to where in the code this exception is being thrown? Understandhing which Azure service you are trying to access at the time of the exception might help narrow down the issue.

I do see some reports on StackOverflow and Microsoft Learn Q&A about others having encountered a similar error when trying to access Azure OpenAI, and I unfortunately am not seeing many answers to solving it. If you are using Azure OpenAI, it might be helpful to know which model you are trying to access, and if you have been able to access any different ones or if you are seeing this error across the board.

**Comment by lynnaloo** [comment]
@sofiangava Look at your `appsettings.Development.json` file and verify that your API key and endpoint url are correct (including the trailing slash on the url). I ran into this same issue and it was due to a typo when I defined my configuration.

**Comment by lgmorand** [comment]
I also found someone having the issue with a typo in the model name

**Comment by evchaki** [comment]
@sofiangava  can you try this again with the latest version.  I just tried to recreate the bug and I was not able to.

**Comment by visbond** [comment]
My team was getting the same error in Azure AI. The root cause was that some services are automatically created in another region if they are not available in your region. Our entire Azure workloads are in Australia, but when we created the document intelligence service, it silently got created in East US.

Due to this, when you see the Endpoints & Keys section of the dashboard, it will show where you created it (an Australian region in our case), but the actual AI service is running from East US, causing a key & region mismatch. The only place where we could see this contrasting location was in Cost Management > Cost Analysis > Resources.

It could possibly be because AI services are not rolled out worldwide, so there is a higher probability of they ending up in a different region than where the keys and endpoint are defined. We created a new document intelligence resource directly in East US, and used the keys and endpoint from there, and it started working without any problem. We deleted the old resource.

**Comment by Brain2000** [comment]
I'm getting this issue now, and there still is not a good answer. I simply followed the directions to create an Azure OpenAI resource, then deploy a model from the OpenAI foundry. The deployment type is "Global Standard" and the OpenAI resource is eastus. I have triple checked that the key, URL, and deployment name are correct in SSMS. It just doesn't work.

**Comment by Brain2000** [comment]
I found more information. It looks like Foundry isn't talking to Azure properly when creating a new model.
I put this OpenAI resource into a resource group called "Group2" in Azure. It exists and I can see the resource in it.

BatchARMResponseError
    at Dl (https://ai.azure.com/assets/manualChunk_common_core-72ceb9af.js:5:265844)
    at async So (https://ai.azure.com/assets/manualChunk_common_core-72ceb9af.js:5:275019

<img width="1595" height="370" alt="Image" src="https://github.com/user-attachments/assets/90895616-4882-408c-a021-11aab28a8ff2" />
