### ISSUE TITLE
Chat Copilot App stops working after enabling WebSearcher Plugin

### ISSUE THREAD

**Issue by karthikkc24** [microsoft/chat-copilot#762]
Description:
Chat Copilot App stops working after enabling WebSearcher Plugin.

To Reproduce:
1. After deploying plugin
2. Launch the Chat Copilot App and enable WebSearcher Plugin
3. After enabling WebSearcher Plugin, start interacting with Chat Copilot App. Error: Unable to generate bot experience. Deatils: Error: 500 Internal Server Error.

Expected behavior:
Expecting Chat Copilot App to interact and suggest/reply to the ask.

Screenshots:
![image](https://github.com/microsoft/semantic-kernel/assets/83394010/95f0aa25-2bcd-41e8-a082-ad191fa532f3)

Platform:
 - OS: Windows
 - IDE: VS Code

**Comment by UTMark** [comment]
Microsoft, please correctly me if I'm wrong but as far as I understand it, this happened due to semantic kernel 1.0.x and its incompatibility with Planner (as now replaced with handlebars). However, the migration had started but its status is currently unknown as seen here: #703 

Since I don't work for Microsoft and don't know how everything works, it may be possible that it doesn't resolve the issue once they have completed the migration of semantic kernel 1.x support.

**Possible workaround:**
When you deploy, it fetches the latest version of the semantic kernel from github and downloads and installs it automatically. This means that if it worked one day, and you re-deployed it after they released 1.0 RC1 (or higher) it would have broken the search plugin.

It may be possible to overwrite this by obtaining an earlier version of the SK from an older tag. ie: https://github.com/microsoft/chat-copilot/releases/tag/0.7

However, when I tried this, I wasn't able to successfully do it but perhaps someone else can get it to work on the latest release.

**Comment by karthikkc24** [comment]
Thank you @UTMark for your guidance. Will try this.

**Comment by karthikkc24** [comment]
Hi @UTMark,

I have tried the workaround mentioned above, but it didn't work. Facing the same error, Error: Unable to generate bot experience. Details: Error: 500 Internal Server Error.

**Comment by ezar** [comment]
I solved this error changing WebSearcher plugin manifest:
```
        var pluginManifest = new PluginManifest()
        {
            NameForModel = "WebSearcher",
            NameForHuman = "WebSearcher",
            DescriptionForModel = "Searches the web",
            DescriptionForHuman = "Searches the web",
            Auth = new PluginAuth(),
            Api = new PluginApi()
            {
                Type = "openapi",
                Url = $"{req.Url.Scheme}://{req.Url.Host}:{req.Url.Port}/swagger.json"
            },
            LogoUrl = $"{req.Url.Scheme}://{req.Url.Host}:{req.Url.Port}/.well-known/icon",
        };
```
