### ISSUE TITLE
How to integrating Chat Functionality with Handlebars Planner Invocation? 

### ISSUE THREAD

**Issue by glenq** [microsoft/chat-copilot#879]
## Question:
Is there any succession or another way to implement my requirement?

### Scenario:
1. I have several article templates that can be retrieved using `TemplateLibraryPlugin`.
2. I want AI to generate an article and utilize a template specified by the user.

### Approach:
1. I've created a Handlebars plan template named `articleTemplate.txt` and intend to automate function invocation.
2. The draft content of the article is sourced from chat history or an uploaded document (`ChatPlugin-ExtractChatHistory`), while the template is sourced from `TemplateLibraryPlugin`.

### Issue:
When automating the invocation of Handlebars functions, the "Chat" function of "ChatPlugin" does not execute. Consequently, the function result cannot be sent to the client via WebSocket.
> I have changed the invoke method from `await kernel.InvokeAsync(chatFunction!,` to `await kernel.InvokePromptAsync`

#### Code:
```
kernel.ImportPluginFromType<TemplateLibraryPlugin>();

string dir = System.IO.Directory.GetCurrentDirectory();
string template = await System.IO.File.ReadAllTextAsync($"{dir}/aritcleTemplate.txt");

var writeArtileFunction = kernel.CreateFunctionFromPrompt(
    new()
    {
        Template = template,
        TemplateFormat = "handlebars"
    }, new HandlebarsPromptTemplateFactory()
);
kernel.ImportPluginFromFunctions("WriteArticlePlugin", new List<KernelFunction> { writeArtileFunction });

OpenAIPromptExecutionSettings settings = new()
{
    ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions,
};

var result = await kernel.InvokePromptAsync(ask.Input, new(contextVariables, new Dictionary<string, PromptExecutionSettings>() { { PromptExecutionSettings.DefaultServiceId, settings } }));

```
#### Handlebars Plan (`aritcleTemplate.txt`)
```
{{!-- Step 1: Extract chat history --}}
{{set "chatHistory" (ChatPlugin-ExtractChatHistory chatId=@root.chatId tokenLimit=32768) }}

{{!-- Step 2: Retrieve the article template by its name --}}
{{set "template" (TemplateLibraryPlugin-GetArticleTemplateByName templateName=templateName) }}

{{!-- Step 3: Replace the {{draft_content}} placeholder in the article template with the actual draft content from the chat history --}}
{{set "article" (replace template "{{draft_content}}" chatHistory) }}

{{!-- Step 4: Print out the final, formed article --}} 
{{json article}}
```

**Comment by daleche-sh** [comment]
@teresaqhoang , my team was blocked by this issue for a couple of weeks, any recommendation to solve this problem?

**Comment by teresaqhoang** [comment]
Hi @daleche-sh, apologies, I completely missed any notification for this issue. 

Looks like your issue lies in Step 3, you need to add a backslash to escape the handlebars since you're using it as a raw string. Otherwise, it'll try to find a function or variable and fail with a null exception error.
```
{{set "article" (replace template "\{{draft_content}}" chatHistory) }}
```

You might have to do the same with the actual comment, but since it's in a comment, I would expect it to not cause a problem:
```
{{!-- Step 3: Replace the \{{draft_content}} placeholder in the article template with the actual draft content from the chat history --}}
```

**Comment by teresaqhoang** [comment]
Also, since you're working with templates, you can try to leverage the built-in capabilities of Handlebars directly by making it an [in-line partial](https://handlebarsjs.com/guide/partials.html#inline-partials). 

I'm guessing `{{draft_content}}` explicitly exists as a static string in your template? Something like
```
This is my chat history {{draft_content}}. Please summarize the highlights.
```

Since you already know the `chatHistory` variable name, you can change the plan to leverage the template as an in-line partial and pass in the `chatHistory` directly: 

```handlebars
{{!-- Step 1: Extract chat history --}}
{{set "chatHistory" (ChatPlugin-ExtractChatHistory chatId=@root.chatId tokenLimit=32768) }}

{{!-- Step 2: Retrieve the article template by its name --}}
{{set "template" (TemplateLibraryPlugin-GetArticleTemplateByName templateName=templateName) }}

{{!-- Step 2a: Define article template as in-line partial --}}
{{#*inline "useTemplate"}}
  {{template}}
{{/inline}}

{{!-- Step 3: Replace the {{draft_content}} placeholder in the article template with the actual draft content from the chat history --}}
{{set "article" {{> useTemplate draft_content=chatHistory}} }}

{{!-- Step 4: Print out the final, formed article --}} 
{{json article}}
```

Here's a [POC in the HB Sandbox](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23*inline%20%5C%22myPartial%5C%22%7D%7D%5Cn%20%20%7B%7Btemplate%7D%7D%5Cn%7B%7B%2Finline%7D%7D%5Cn%5CnExample%20using%20context%20only%3A%5Cn%7B%7B%3E%20new_partial%7D%7D%5Cn%5Cn%5CnExample%20with%20parameter%20definition%3A%5Cn%7B%7B%3E%20new_partial%20draft_content%3Dchat_history%7D%7D%5Cn%22%2C%22partials%22%3A%5B%7B%22name%22%3A%22new_partial%22%2C%22content%22%3A%22%5C%22This%20is%20my%20chat%20history%20%7B%7Bdraft_content%7D%7D.%20Please%20summarize%20the%20highlights.%5C%22%20%22%7D%5D%2C%22input%22%3A%22%7B%5Cn%20%20template%3A%20%5C%22This%20is%20my%20chat%20history%20%7B%7Bdraft_content%7D%7D.%20Please%20summarize%20the%20highlights.%5C%22%2C%5Cn%20%20%20%20chat_history%3A%20%5C%22Chat%20History%5C%22%2C%5Cn%20%20%20%20draft_content%3A%20%5C%22Some%20Content%5C%22%5Cn%7D%5Cn%22%2C%22output%22%3A%22%5CnExample%20using%20context%20only%3A%5Cn%5C%22This%20is%20my%20chat%20history%20Some%20Content.%20Please%20summarize%20the%20highlights.%5C%22%20%5Cn%5CnExample%20with%20parameter%20definition%3A%5Cn%5C%22This%20is%20my%20chat%20history%20Chat%20History.%20Please%20summarize%20the%20highlights.%5C%22%20%22%2C%22preparationScript%22%3A%22%2F%2F%20Handlebars.registerHelper('loud'%2C%20function(string)%20%7B%5Cn%2F%2F%20%20%20%20return%20string.toUpperCase()%5Cn%2F%2F%20%7D)%3B%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.8%22%7D)

**Comment by teresaqhoang** [comment]
If neither of the above helps, please provide the following details so we can troubleshoot:
- Where are you executing this code? Link to your repo would be most helpful.
- Is this line successful? i.e., do you get a result after rendering the HB template or are you seeing an error? Provide the result or error
```c
var result = await kernel.InvokePromptAsync(ask.Input, new(contextVariables, new Dictionary<string, PromptExecutionSettings>() { { PromptExecutionSettings.DefaultServiceId, settings } }));
```

**Comment by daleche-sh** [comment]
> Hi @daleche-sh, apologies, I completely missed any notification for this issue.
> 
> Looks like your issue lies in Step 3, you need to add a backslash to escape the handlebars since you're using it as a raw string. Otherwise, it'll try to find a function or variable and fail with a null exception error.
> 
> ```
> {{set "article" (replace template "\{{draft_content}}" chatHistory) }}
> ```
> 
> You might have to do the same with the actual comment, but since it's in a comment, I would expect it to not cause a problem:
> 
> ```
> {{!-- Step 3: Replace the \{{draft_content}} placeholder in the article template with the actual draft content from the chat history --}}
> ```

@teresaqhoang , it works, thank you so much!!! It's a big step for our project after solving this problem.
